-- ==============================================================================
-- ESQUEMA COMPLETO E POLÍTICAS RLS PARA O SUPABASE
-- Execute este script no "SQL Editor" do painel do Supabase
-- ==============================================================================

-- 1. CRIAÇÃO DAS TABELAS

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  pin TEXT
);

CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  stock_quantity INT DEFAULT 0,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  destination TEXT
);

CREATE TABLE tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number INT NOT NULL,
  status TEXT DEFAULT 'Livre',
  current_waiter_id BIGINT REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id BIGINT REFERENCES tables(id) ON DELETE CASCADE,
  waiter_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'Aberto',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  quantity INT DEFAULT 1,
  observations TEXT,
  status TEXT DEFAULT 'Pendente',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  method TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE cash_registers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT DEFAULT 'Aberto',
  initial_balance DECIMAL(10,2) DEFAULT 0,
  current_balance DECIMAL(10,2) DEFAULT 0,
  opened_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ
);

-- ==============================================================================
-- 2. HABILITAR SEGURANÇA EM NÍVEL DE LINHA (RLS)
-- ==============================================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE cash_registers ENABLE ROW LEVEL SECURITY;

-- Como o sistema não exige autenticação baseada em email/senha no momento (usa um Kiosk mode local),
-- vamos criar políticas que permitem operações pelo "anon" token para acesso total.
-- Nota: Em produção externa, o correto é amarrar isso a usuários Autenticados.

CREATE POLICY "Acesso Total Anonimo - Users" ON users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Categories" ON categories FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Products" ON products FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Tables" ON tables FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Orders" ON orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Order_items" ON order_items FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Payments" ON payments FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acesso Total Anonimo - Cash_registers" ON cash_registers FOR ALL USING (true) WITH CHECK (true);

-- ==============================================================================
-- 3. INSERÇÃO DE DADOS INICIAIS (SEED)
-- ==============================================================================

-- Criar primeiro usuário admin
INSERT INTO users (name, role, pin) VALUES ('Administrador', 'Admin', '1234');
INSERT INTO users (name, role, pin) VALUES ('Joao Garçom', 'Garçom', '0000');

-- Criar 5 Mesas iniciais
INSERT INTO tables (number) VALUES (1), (2), (3), (4), (5);

-- ==============================================================================
-- 4. CONFIGURAÇÃO DO REAL-TIME PARA O KDS
-- ==============================================================================
-- Habilita as transmissões WebSocket para a tabela de itens
alter publication supabase_realtime add table order_items;
